upstream coord {
    server 192.168.254.130:9200;
    server 192.168.254.131:9200;
}
    
server {
    listen 443 ssl;
    
    ssl_certificate     /etc/nginx/lb.crt;
    ssl_certificate_key /etc/nginx/lb.key;
    
       location / {
        proxy_pass https://coord;
    
        proxy_ssl_server_name off;
        proxy_ssl_verify off;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    
        proxy_buffering off;
    }
}